<?php
require_once('./Services/UIComponent/classes/class.ilUserInterfaceHookPlugin.php');
require_once('./Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/Subscription/classes/class.ilDynamicLanguage.php');

/**
 * Class ilSubscriptionPlugin
 *
 * @author Fabian Schmid <fs@studer-raimann.ch>
 */
class ilSubscriptionPlugin extends ilUserInterfaceHookPlugin implements ilDynamicLanguageInterface {

	/**
	 * @return string
	 */
	public function getCsvPath() {
		$path = substr(__FILE__, 0, strpos(__FILE__, 'classes')) . 'lang/';
		if (file_exists($path . 'lang_custom.csv')) {
			$file = $path . 'lang_custom.csv';
		} else {
			$file = $path . 'lang.csv';
		}

		return $file;
	}


	/**
	 * @return string
	 */
	public function getAjaxLink() {
		return false;
	}


	/**
	 * @param $key
	 *
	 * @return mixed
	 */
	public function getDynamicTxt($key) {
		return ilDynamicLanguage::getInstance($this, ilDynamicLanguage::MODE_PROD)->txt($key);
	}


	/**
	 * @var ilSubscriptionPlugin
	 */
	protected static $instance;


	/**
	 * @return ilSubscriptionPlugin
	 */
	public static function getInstance() {
		if (!isset(self::$instance)) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * @return string
	 */
	public function getPluginName() {
		return 'Subscription';
	}


	/**
	 * @return bool
	 * @throws ilPluginException
	 */
	public function updateDatabase() {
		$this->checkPreconditions();

		return parent::updateDatabase(); // TODO: Change the autogenerated stub
	}


	/**
	 * @return bool
	 * @throws ilPluginException
	 */
	public function beforeActivation() {
		$this->checkPreconditions();

		return true;
	}


	/**
	 * @return ilCtrl
	 * @throws ilPluginException
	 */
	protected function checkPreconditions() {
		/**
		 * @var $ilCtrl ilCtrl
		 */
		require_once('./Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/Subscription/classes/class.subscr.php');
		$path = strstr(__FILE__, 'Services', true) . 'Libraries/ActiveRecord/';
		global $ilCtrl;

		if (subscr::is44() && $ilCtrl->lookupClassPath('ilRouterGUI') === NULL) {
			throw new ilPluginException('Please install ilRouterGUI, see https://github.com/studer-raimann/RouterService');
		}
		if (subscr::is44() && (!is_file($path . 'class.ActiveRecord.php') OR !is_file($path . 'class.ActiveRecordList.php'))) {
			throw new ilPluginException('Please install ActiveRecord, see https://github.com/studer-raimann/ActiveRecord');
		}

		return $ilCtrl;
	}
}

?>
